@startuml
actor 利用者
rectangle {
    利用者 --> (スタジアムを検索する)
    利用者 --> (スタジアムの情報を閲覧する)

    (スタジアムの情報を閲覧する) --|> (基本情報を閲覧する)
    (スタジアムの情報を閲覧する) --|> (グルメ情報を閲覧する)
    (スタジアムの情報を閲覧する) --|> (アクセス方法を閲覧する)
    (スタジアムの情報を閲覧する) --|> (スタジアム近辺の観光地を調べる)
}
@enduml