@startuml
actor ユーザー
boundary スタジアム詳細画面
control スタジアム関連システム
entity データベース

ユーザー -> スタジアム詳細画面: タブで「周辺施設」を押下
スタジアム詳細画面 -> スタジアム関連システム: 周辺施設情報を取得リクエスト
スタジアム関連システム -> データベース: スタジアム周辺の人気施設情報を取得
alt 周辺施設情報が存在する場合
    データベース -> スタジアム関連システム: 周辺施設情報を返却
    スタジアム関連システム -> スタジアム詳細画面: 人気施設情報を表示
else 周辺施設情報が存在しない場合
    スタジアム関連システム -> スタジアム詳細画面: 「周辺施設情報がありません」と表示
end
@enduml
