@startuml
actor ユーザー
boundary スタジアム検索画面
boundary スタジアム詳細画面
control スタジアム関連システム
entity データベース

ユーザー -> スタジアム検索画面: スタジアム一覧から特定のスタジアムを選択
スタジアム検索画面 -> スタジアム関連システム: スタジアム詳細情報リクエスト
スタジアム関連システム -> データベース: スタジアム情報を取得
データベース -> スタジアム関連システム: スタジアム情報を返却
スタジアム関連システム -> スタジアム詳細画面: スタジアム詳細画面に遷移
@enduml
